CREATE TABLE IF NOT EXISTS erp_user (
    id            INT IDENTITY(1,1) PRIMARY KEY,
    created_at    DATETIME2    DEFAULT CURRENT_TIMESTAMP,
    center_code   VARCHAR(50),
    role_key      VARCHAR(50),
    user_code     VARCHAR(50),
    user_id       VARCHAR(100) NOT NULL,
    user_name     VARCHAR(100),
    password_hash VARCHAR(255),
    salt          VARCHAR(100),
    type          VARCHAR(20),
    user_phone    VARCHAR(20),
    is_han        BIT          DEFAULT 0,
    is_book       BIT          DEFAULT 0,
    use_yn        BIT          DEFAULT 1,
    is_clinic     BIT          DEFAULT 0
);

CREATE TABLE IF NOT EXISTS erp_student (
    id                    INT IDENTITY(1,1) PRIMARY KEY,
    created_at            DATETIME2   DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME2   DEFAULT CURRENT_TIMESTAMP,
    center_code           VARCHAR(50),
    grade_key             VARCHAR(50),
    status_key            VARCHAR(50),
    school                VARCHAR(100),
    student_id            VARCHAR(100),
    student_name          VARCHAR(100),
    address               VARCHAR(255),
    address_detail        VARCHAR(255),
    app_id                VARCHAR(100),
    app_password          VARCHAR(255),
    app_token             VARCHAR(255),
    birth                 VARCHAR(20),
    profile_img           VARCHAR(255),
    consult_key           VARCHAR(50),
    billing_phone         VARCHAR(20),
    serial_num            VARCHAR(100),
    gender                BIT         DEFAULT 0,
    student_privacy_agree BIT         DEFAULT 0,
    is_hoho               BIT         DEFAULT 0,
    sub_han               BIT         DEFAULT 0,
    sub_book              BIT         DEFAULT 0,
    sub_hoho              BIT         DEFAULT 0
);
